# Generated by Django 4.0.4 on 2022-05-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
