# Generated by Django 4.0.5 on 2022-08-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0005_myuser_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Qwerty', 'verbose_name_plural': 'Questions'},
        ),
    ]
