# Generated by Django 4.0.5 on 2022-08-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0007_role_organisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={},
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='user',
        ),
    ]
