# Generated by Django 4.0.5 on 2022-08-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0009_remove_myuser_image_delete_organisation_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
