# Generated by Django 4.0.5 on 2022-08-16 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0010_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='city',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organisation',
            name='user',
            field=models.ForeignKey(default='5432', on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
