# Generated by Django 4.0.5 on 2022-08-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0024_alter_employee_org_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='org_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='discy.organisation'),
        ),
    ]
