# Generated by Django 4.0.5 on 2022-08-17 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0027_remove_myuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='employee',
        ),
        migrations.AddField(
            model_name='organisation',
            name='employee',
            field=models.ManyToManyField(null=True, related_name='organisation', to=settings.AUTH_USER_MODEL),
        ),
    ]
