# Generated by Django 4.0.5 on 2022-08-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0028_remove_organisation_employee_organisation_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='role',
        ),
    ]
