# Generated by Django 4.0.5 on 2022-08-17 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0029_remove_organisation_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgmanagement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OrgManagement',
                'verbose_name_plural': 'OrgManagements',
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='orgmanagement',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgmanagement', to='discy.organisation'),
        ),
    ]
