# Generated by Django 4.0.5 on 2022-08-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0030_orgmanagement_organisation_city_delete_employee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
