# Generated by Django 4.0.5 on 2022-08-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0032_orgmanagement_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgManagement',
            new_name='UserOrg',
        ),
    ]
