# Generated by Django 4.0.5 on 2022-08-17 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0033_rename_orgmanagement_userorg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorg',
            name='role',
        ),
        migrations.AlterField(
            model_name='userorg',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orgmanagement', to='discy.organisation'),
        ),
    ]
