# Generated by Django 4.0.5 on 2022-08-17 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0035_alter_userorg_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorg',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userorg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userorg',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userorg', to='discy.organisation'),
        ),
    ]
