# Generated by Django 4.0.5 on 2022-08-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0038_userorg_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='org',
            field=models.ManyToManyField(blank=True, related_name='myuser', through='discy.UserOrg', to='discy.organisation'),
        ),
    ]
