# Generated by Django 4.0.5 on 2022-08-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0040_alter_userorg_employee_alter_userorg_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorg',
            old_name='name',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='userorg',
            old_name='employee',
            new_name='user',
        ),
    ]
