# Generated by Django 4.0.5 on 2022-08-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0042_alter_userorg_organisation_alter_userorg_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='org',
        ),
    ]
