# Generated by Django 4.0.5 on 2022-08-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0043_remove_myuser_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorg',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discy.organisation'),
        ),
    ]
