# Generated by Django 4.0.5 on 2022-08-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0045_alter_question_options_alter_userorg_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='city',
            field=models.CharField(max_length=30, null=None),
        ),
    ]
