# Generated by Django 4.0.5 on 2022-08-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discy', '0051_alter_organisation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
